name: Build & Lint

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  node-version: "18"
  path: "KoLmafia"

jobs:
  push:
    runs-on: ubuntu-latest
    needs: [ ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn run build

      - name: Push to Release
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: ${{ env.path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit hash and message that prompted this workflow
          SKIP_EMPTY_COMMITS: true
